### ISSUE TITLE
Disable scrolling down the home

### ISSUE THREAD

**Issue by adrienrichmond** [8bitPit/Niagara-Issues#2884]
### Describe the solution you'd like

On most Android models, the downward scroll opens the notification bar menu. However, when we scroll down, this also moves the icons from the menu down. For more sobriety, adding an option to freeze icons would be ideal (unless the number of icons passes the screen). 

![Screenshot_20240905_194601_Niagara Launcher](https://github.com/user-attachments/assets/f3092129-8eee-42d3-bcb0-c4b418be0704)
![Screenshot_20240905_194557_Niagara Launcher](https://github.com/user-attachments/assets/99419265-77a2-4290-ac24-ad6de02ee2df)

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by contact-maximux** [comment]
case invalid
- icon are perfectly fit on screen
- one notification came under one favorite icon, height changed
- one more notification, height changed
- two 
- three
- Oh somone play musicplayer and thing move down more. Height changed.

**only solution is make niagra button 4 way gesture**
- Down: notification
- Up:Search
- Left: move to microsoft feed page. Niagra will add it, i think
- Right: Clear all notification

**Comment by adrienrichmond** [comment]
> Case Invalid.
Icon are perfectly fit on screen.
> - One notification came under one favorite icon, height changed.
> - One more notification, height changed.
> - Two
> - Three.
Oh somone play musicplayer and thing move down more. Height changed.
>
> **Only solution is make Niagra Button 4 way Gesture**.
> - Down: notification
> - Up:Search
> - Left: move to Microsoft feed page. Niagra will add it, I think.
> - Right: Clear all notification
>

Customizing the button looks good to me.

**Comment by contact-maximux** [comment]
@adrienrichmond Thereare two movement
**UP**
**DOWN**
both are problematic incase of screen content more that screen height. I got problem in opening search by swipe up. I always have to swipeup first, then again swipe for search screen

**Comment by NiagaraSupport** [comment]
Hey there, thanks for the suggestion.
This should only happen if you have scrollable content off screen. If you [move the widget](https://help.niagaralauncher.app/article/156-move-clock#:~:text=Long%2Dpress%20the%20clock%20%3E%20Move%20widget%20%3E%20use%20the%20arrows%20on,arrows%20on%20the%20slider%20to%20move%20the%20clock%20up%20and%20down) up a bit the position should be fixed after swiping.

**Comment by gitsoncpu** [comment]
I have no scrollable content off screen and the position is still not fixed.  I have removed all favorites and widgets and it still scrolls. Thanks.

**Comment by gitsoncpu** [comment]
I have no scrollable off screen content and it still is not fixed.  Tried removing all widgets and favorites and it seems to have the same behavior, requiring a longer swipe down to access notifications.
