### ISSUE TITLE
moving favourites

### ISSUE THREAD

**Issue by cauerego** [8bitPit/Niagara-Issues#367]
#bug

there's apparently no way to scroll up and down. other than moving an app to the edge of the screen.

get about 20 favourites and try rearranging them in a completely different order, as to emulate how one would probably go around.

#feature request

remove the moving screen all together, and do it the regular way, by holding the app. for such a small list, there's no need for a dedicated screen.

**Comment by 8bitPit** [comment]
You're right, should fix it.

> remove the moving screen all together, and do it the regular way, by holding the app.
You can move your favorite apps only in a dedicated list, because I'll add contextual features in the feature, so some apps are placed at the top when specific events occur.

**Comment by cauerego** [comment]
but will that affect the order of favourites as well?

**Comment by 8bitPit** [comment]
Yeah it could affect the order, a music player shows up at the top (or moves to the top if it you added it to your favorites) while headphones are plugged in.

**Comment by cauerego** [comment]
so i still don't follow why a dedicated re-ordering apps list is needed! :)

**Comment by 8bitPit** [comment]
Because your list on the home screen could be out of order.

**Comment by cauerego** [comment]
nevermind... :D
